// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * PaymentGateway Contract
 *
 * Flow:
 * 1. Customer calls pay() with invoiceId + merchant address + ETH
 * 2. Contract emits PaymentReceived event
 * 3. Backend (NestJS) listens to event via ethers.js
 * 4. Backend verifies & updates invoice status in database
 * 5. Merchant calls withdraw() to claim their ETH
 */
contract PaymentGateway {
    // ─── State Variables ───────────────────────────────────────────────────────

    address public owner;

    struct Payment {
        address payer;
        address merchant;
        uint256 amount;
        uint256 timestamp;
    }

    // invoiceId (bytes32) => Payment detail
    mapping(bytes32 => Payment) public payments;

    // merchant address => claimable balance
    mapping(address => uint256) public merchantBalances;

    // ─── Events ────────────────────────────────────────────────────────────────
    // Backend (ethers.js) listens to these events to verify payments

    event PaymentReceived(
        bytes32 indexed invoiceId,
        address indexed payer,
        address indexed merchant,
        uint256 amount,
        uint256 timestamp
    );

    event Withdrawn(address indexed merchant, uint256 amount);

    // ─── Modifiers ─────────────────────────────────────────────────────────────

    modifier onlyOwner() {
        require(msg.sender == owner, "PaymentGateway: not owner");
        _;
    }

    modifier validAddress(address addr) {
        require(addr != address(0), "PaymentGateway: zero address");
        _;
    }

    // ─── Constructor ───────────────────────────────────────────────────────────

    constructor() {
        owner = msg.sender;
    }

    // ─── External Functions ────────────────────────────────────────────────────

    /**
     * Customer pays for an invoice.
     * @param invoiceId  Unique invoice ID generated by the backend (bytes32)
     * @param merchant   Merchant wallet address that will receive the funds
     */
    function pay(bytes32 invoiceId, address merchant)
        external
        payable
        validAddress(merchant)
    {
        // Checks
        require(msg.value > 0, "PaymentGateway: amount must be > 0");
        require(
            payments[invoiceId].amount == 0,
            "PaymentGateway: invoice already paid"
        );

        // Effects — update state BEFORE any external interaction
        payments[invoiceId] = Payment({
            payer: msg.sender,
            merchant: merchant,
            amount: msg.value,
            timestamp: block.timestamp
        });

        merchantBalances[merchant] += msg.value;

        // Emit event — backend listens to this
        emit PaymentReceived(
            invoiceId,
            msg.sender,
            merchant,
            msg.value,
            block.timestamp
        );
    }

    /**
     * Merchant withdraws their accumulated balance.
     * Uses CEI pattern to prevent reentrancy attacks.
     */
    function withdraw() external {
        uint256 balance = merchantBalances[msg.sender];

        // Checks
        require(balance > 0, "PaymentGateway: no balance to withdraw");

        // Effects — zero out BEFORE transferring (reentrancy protection)
        merchantBalances[msg.sender] = 0;

        // Interactions — send ETH using low-level call (recommended over transfer)
        (bool success, ) = msg.sender.call{value: balance}("");
        require(success, "PaymentGateway: transfer failed");

        emit Withdrawn(msg.sender, balance);
    }

    // ─── View Functions ────────────────────────────────────────────────────────

    function getPayment(bytes32 invoiceId)
        external
        view
        returns (Payment memory)
    {
        return payments[invoiceId];
    }

    function getMerchantBalance(address merchant)
        external
        view
        returns (uint256)
    {
        return merchantBalances[merchant];
    }

    function isInvoicePaid(bytes32 invoiceId) external view returns (bool) {
        return payments[invoiceId].amount > 0;
    }
}
